export const adjectives = [
  { word: "zielony", gender: 0 },
  { word: "niebieska", gender: 1 },
  { word: "czerwony", gender: 0 },
  { word: "żółta", gender: 1 },
  { word: "pomarańczowy", gender: 0 },
  { word: "fioletowa", gender: 1 },
  { word: "plamiasty", gender: 0 },
  { word: "geometryczna", gender: 1 },
  { word: "ceglany", gender: 0 },
  { word: "metalowa", gender: 1 },
  { word: "piankowy", gender: 0 },
  { word: "ceramiczny", gender: 0 },
  { word: "płonąca", gender: 1 },
  { word: "mistyczna", gender: 1 },
];

export const nouns = [
  { word: "szlug", gender: 0 },
  { word: "autobus", gender: 0 },
  { word: "kamienica", gender: 1 },
  { word: "pies", gender: 0 },
  { word: "kotka", gender: 1 },
  { word: "sąsiadka", gender: 1 },
  // { word: "pszczoła", gender: 1 },
  // { word: "rekin", gender: 0 },
  // { word: "mucha", gender: 1 },
  // { word: "ryś", gender: 0 },
  // { word: "biedronka", gender: 1 },
  // { word: "smok", gender: 0 },
  // { word: "czarodziejka", gender: 1 },
  // { word: "rycerz", gender: 0 },
  // { word: "wróżka", gender: 1 },
  // { word: "elf", gender: 0 },
  // { word: "nimfa", gender: 1 },
  // { word: "krasnolud", gender: 0 },
  // { word: "syrena", gender: 1 },
  // { word: "golem", gender: 0 },
  // { word: "wiedźma", gender: 1 },
  // { word: "troll", gender: 0 },
  // { word: "harpia", gender: 1 },
  // { word: "czarny rycerz", gender: 0 },
  // { word: "zaklinacz", gender: 0 },
  // { word: "księżniczka", gender: 1 },
  // { word: "goblin", gender: 0 },
  // { word: "olbrzym", gender: 0 },
  // { word: "król", gender: 0 },
  // { word: "królowa", gender: 1 },
  // { word: "mag", gender: 0 },
  // { word: "czarownica", gender: 1 },
  // { word: "alchemik", gender: 0 },
  // { word: "smoczyca", gender: 1 },
  // { word: "paladyn", gender: 0 },
  // { word: "czarodziej", gender: 0 },
  // { word: "wampir", gender: 0 },
  // { word: "druid", gender: 0 },
  // { word: "demon", gender: 0 },
  // { word: "strażniczka", gender: 1 },
  // { word: "zjawa", gender: 1 },
  // { word: "upiór", gender: 0 },
];
